# metadata for training on concentric dataset

### Names ###
project_name: Chaotic
name: CLSTM

### Save and load dataset/weights etc. ###
dataset: chaotic
dataset_dir: data/datasets/chaotic/processed/
save_dir: models/weights/chaotic/
save_name: CLSTM
load_weights: false
weights_file: ./model

# Use WandB API
wandb: true
wandb_dir: data/evaluation/wandb/chaotic/CLSTM

### Model ###
architecture: CLSTM
num_features: 64

### Training process ###
lr: 0.0001
optimizer: Adam
loss_fn: MSE
batch_size: 4

### Experiment-specific quantities ###
epochs: 16
depth: 1
depths: null

time_step: 1
time_steps: null

### Internet connection? Use live-logger via WandB ### 
online: 0



